project:
  type: manuscript

execute:
  freeze: true

format:
  html:
    toc: true
    comments:
      hypothesis: false
    title-block-style: manuscript
    theme:
      light: flatly
      dark: darkly
  docx: default
  jats: default
  agu-pdf: default



